# 수업에 사용될 라이브러리 설치

In [ ]:
!ls   # 윈도우 사용자의 경우 -> dir 
# pip install numpy
# !pip install -r requirements.txt

sample_data


# Numpy 소개

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
import numpy as np

## ndarray dtype

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# indexing이 list와 방식이 같음
a[0]

1

In [ ]:
a

array([1, 2, 3])

- append() 같은 함수가 없음 -> 즉, python의 list와는 다른 data type임

## Universal function

In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]

new_list = []
for e1, e2 in zip(a, b):
    new_list.append(e1 + e2)
new_list

[5, 7, 9]

In [ ]:
a + b

[1, 2, 3, 4, 5, 6]

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
# 길이가 길어도 근사적으로 1초가 걸린다
a + b

array([5, 7, 9])

In [ ]:
# np.sum
# np.abs
# np.log
# np.exp
# np.isnan
# ...

- n차원 array

In [ ]:
a = np.array([  [1, 2],  [3, 4]   ])
a

array([[1, 2],
       [3, 4]])

In [ ]:
# readability 높이기
a = np.array(
    [
        [1, 2],
        [3, 4],
    ]
)

In [ ]:
a[0][1]

2

In [ ]:
a + a

array([[2, 4],
       [6, 8]])