## presetting

In [2]:
#preset1 - 패키지 opt1 - 구글드라이브에 설치하기
import os, sys
from google.colab import drive

#preset1 -  Colab Notebooks 안에 .env 폴더에 패키지 저장 ( 심볼링 링크가 작동 안된다. )
"""
drive.mount('/content/drive')
my_path = '/content/notebooks'
os.symlink('/content/drive/My Drive/_ColabNotebooks/.env', my_path) # 기존 path를 바꿔치기
sys.path.insert(0, my_path)
"""
#preset1 -  Dependency - 위 preinstall 작업을 안하면, 세션 할당시 매번 install
"""
!pip install --target=$my_path finance_datareader
"""

#preset1 - 패키지 opt2 - 매번 설치하기

# !pip install finance_datareader

#preset -  my_data있는 드라이브 마운트
drive.mount('/content/drive')
prefix_path = "/content/drive/My Drive/_ColabNotebooks/"


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#preset - 주피터 노트북 여러줄 출력
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#preset - pandas
pd.set_option("display.float_format",lambda x: '%.3f'%x) # 소수점 6자리 > 3자리만 보여달라
pd.set_option("max_columns",None) # 컬럼을 ... 으로 요약하지 마라 ( row는 요약되어있다.)
# pd.DataFrame(np.random.randn(1000,300))

#preset - matplotlib
# 매번 시각화가 inline으로 나오도록.
%matplotlib inline

"\ndrive.mount('/content/drive')\nmy_path = '/content/notebooks'\nos.symlink('/content/drive/My Drive/_ColabNotebooks/.env', my_path) # 기존 path를 바꿔치기\nsys.path.insert(0, my_path)\n"

'\n!pip install --target=$my_path finance_datareader\n'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## numpy 요약

### numpy eg

In [16]:
n1 = np.array([1,2,3,4])
n2 = np.array([[1,2,3],[4,5,6]])
n3 = np.arange(1,5,1)
n2.sum(),n2.mean(),n2.T # 합계,평균,전치 등 
n1+n3 # 덧셈 연산

(21, 3.5, array([[1, 4],
        [2, 5],
        [3, 6]]))

array([2, 4, 6, 8])

## Series 요약 -1

In [ ]:
"""
#시리즈

## 시리즈 생성 
- 1.배열+인덱스배열 
- 2.dict


## 메타 정보 읽기
- np.nan 타입이 있다. (특별한 타입, null같은존재??)
- len(s)    ( nan 포함 길이 )
- s.shape   ( nan 포함 길이 )
- s.count() ( nan 안포함 갯수)

## 읽기

- head,tail (상,하위 요소 읽기)
- index,
- 슬라이싱
 


## 가공
- s.unique    ( nan 포함 )
- s.nunique = 유니크 후 count ( nan 미포함 )
- s.value_counts = 유니크 후 각각의 갯수  ( nan 미포함 )



## 연산
- 덧셈 : index가 있다면 index끼리 연산이 된다.

"""

'\n#시리즈\n\n## 시리즈 생성 \n- 1.배열+인덱스배열 \n- 2.dict\n\n\n## 메타 정보 읽기\n- np.nan 타입이 있다.\n- 길이 len(s) ( nan 포함 )\n- 갯수 s.count ( nan 안포함 )\n- s.shape\n\n## 읽기\n\n- index,\n- 슬라이싱\n- 상(하)위 요소 읽기 head,tail  \n\n\n## 가공\n- s.unique\n- s.nunique = 유니크 후 count\n- s.value_counts = 유니크 후 각각의 갯수\n\n\n\n## 연산\n- 덧셈 : index가 있다면 index끼리 연산이 된다.\n\n'

### Series 요약 -1 eg

In [26]:
s1 = pd.Series([1,2,np.nan],index=['a','b','c'])
s2 = pd.Series({'a':3,'b':2,'c':1})
s1,s2 # dtype float64 (하나라도 nan이면)
s1+s2 # index 얼라인 되어 덧셈

len(s1),s1.shape,s1.count()
s1.unique(),s1.nunique(),s1.value_counts()

(a   1.000
 b   2.000
 c     nan
 dtype: float64, a    3
 b    2
 c    1
 dtype: int64)

a   4.000
b   4.000
c     nan
dtype: float64

(3, (3,), 2)

(array([ 1.,  2., nan]), 2, 2.000    1
 1.000    1
 dtype: int64)

## DF 요약 - 1

In [ ]:
"""
# 데이터 프레임

## 데이터 프레임 create

- [1] dict으로 생성, key값이 *columns, value는 iterable ( 크기에 대한 정렬 필수 )
- [2] 2차원 배열로 생성 ( index의 default는 숫자로 생성된다. 마치 바닐라 2차원 배열처럼 )
* options : index,columns 지정하기

* iterable 객체면 생성이 된다. (range,[ ], np.arange, np.array, pd.Series )
* 시리즈에서는 index가 있었다, 데이터 프레임은 index, columns 가 존재
* value가 Series라면, index를 비교해서 outter join 하게 된다. null 대신 nan 타입이 들어옴

- s2 = s.copy() # 깊은 복사

## 데이터 프레임 update

- 새로운 컬럼 'c4' 추가
*df['c4'] = pd.Series([1,2,3,4], index=[0, 1, 2, 10])
* index align check

- index
s.index : index 이름 자체를 바꾸기
s2.index = s2.index.astype(int) # index의 형변환. str > int (리턴)
df.set_index("c5") : 특정 컬럼을, 인덱스 컬럼으로 변경 후 (리턴)
df.reset_index() : 인덱스 컬럼 제거 후 (리턴)

- Reindexing() : 특정 index만 골라내 (리턴)
*s2.reindex(['a', 'f'], fill_value=0)  # fill 0 insteand of Nan
*s3.reindex(np.arange(0,7), method='ffill') # forward fill - nan을 이전값으로 매꿔라.
"""



"\n# 데이터 프레임\n\n## 데이터 프레임 create\n\n- [1] dict으로 생성, key값이 *columns, value는 iterable ( 크기에 대한 정렬 필수 )\n- [2] 2차원 배열로 생성 ( index의 default는 숫자로 생성된다. 마치 바닐라 2차원 배열처럼 )\n* options : index,columns 지정하기\n\n* iterable 객체면 생성이 된다. (range,[ ], np.arange, np.array, pd.Series )\n* 시리즈에서는 index가 있었다, 데이터 프레임은 index, columns 가 존재\n* value가 Series라면, index를 비교해서 outter join 하게 된다. null 대신 nan 타입이 들어옴\n\n\n## 데이터 프레임 update\n- 새로운 컬럼 'c4' 추가\n*df['c4'] = pd.Series([1,2,3,4], index=[0, 1, 2, 10])\n* index align check\n"

### DF 요약 - 1 eg

In [57]:
df1 = pd.DataFrame({
    'c1':[1,2,3],
    'c2':[3,4,5],
    'c3':[7,8,9]
},index=range(0,3,1))
df2 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],
                   index=range(0,3,1),
                   columns=['c1','c2','c3']
                  )
df1.index,df2.index # RangeIndex 타입으로
df3 = df1+df2 # 인덱스 얼라인 되어 연산 가능 
df3.describe() # 개요
df3.index = df3.index.astype(str) # index 형변환
df3 = df3.set_index('c1') # c1 컬럼을 인덱스로 임시지정
df3 = df3.reset_index() # 인덱스 리셋 (초기인덱스는 제거됨)

(RangeIndex(start=0, stop=3, step=1), RangeIndex(start=0, stop=3, step=1))

c1     c2     c3
count  3.000  3.000  3.000
mean   6.000  9.000 14.000
std    4.000  4.000  4.000
min    2.000  5.000 10.000
25%    4.000  7.000 12.000
50%    6.000  9.000 14.000
75%    8.000 11.000 16.000
max   10.000 13.000 18.000

In [68]:
df1 = pd.DataFrame({
    'c1':pd.Series([1,2,3],index=range(0,3)),
    'c2':pd.Series([np.nan,4,5],index=range(0,3))
})
df1['c3'] = pd.Series([5,6,7],index=range(0,3))
df1

c1    c2  c3
0   1   nan   5
1   2 4.000   6
2   3 5.000   7

In [77]:
s1 = pd.Series(['red','green','blue'],index=[0,3,5])
s1.reindex(range(0,10,1),fill_value='color')
s1.reindex(range(0,10,1),method="ffill")

0      red
1    color
2    color
3    green
4    color
5     blue
6    color
7    color
8    color
9    color
dtype: object

0      red
1      red
2      red
3    green
4    green
5     blue
6     blue
7     blue
8     blue
9     blue
dtype: object

In [93]:
# eg) ffill을 이용해서, 비어있는 주가 데이터를 채워보자.
import FinanceDataReader as fdr
# 삼성전자
df1 = fdr.DataReader("005930", '2018-01-02', '2018-10-30') # 코드명,조회시작,조회끝 날짜
# KODEX 200 (ETF)
df2 = fdr.DataReader("069500", '2018-01-02', '2018-10-30')

# 가정 - 01월03일 데이터가 없어서, 전날 데이터로 채움
df1 = df1.drop(pd.to_datetime('2018-01-03'))
df1.reindex(df2.index,method="ffill")

Open   High    Low  Close  Volume  Change
Date                                                  
2018-01-02  51380  51400  50780  51020  169485   0.001
2018-01-04  52120  52180  50640  51080  233909  -0.010
2018-01-05  51300  52120  51200  52120  189623   0.020
2018-01-08  52400  52520  51500  52020  167673  -0.002
2018-01-09  51460  51720  49980  50400  360272  -0.031

Open   High    Low  Close    Volume  Change
Date                                                    
2018-01-02  51380  51400  50780  51020    169485   0.001
2018-01-03  51380  51400  50780  51020    169485   0.001
2018-01-04  52120  52180  50640  51080    233909  -0.010
2018-01-05  51300  52120  51200  52120    189623   0.020
2018-01-08  52400  52520  51500  52020    167673  -0.002
...           ...    ...    ...    ...       ...     ...
2018-10-24  43050  43100  42250  42550  13522825  -0.012
2018-10-25  40600  41550  40550  41000  19338170  -0.036
2018-10-26  41100  41300  40400  41000  14413864   0.000
2018-10-29  40850  41950  40550  41400  14460521   0.010
2018-10-30  41400  43000  41000  42350  14205190   0.023

[202 rows x 6 columns]

Open   High    Low  Close  Volume  Change
Date                                                  
2018-01-02  51380  51400  50780  51020  169485   0.001
2018-01-04  52120  52180  50640  51080  233909  -0.010
2018-01-05  51300  52120  51200  52120  189623   0.020
2018-01-08  52400  52520  51500  52020  167673  -0.002
2018-01-09  51460  51720  49980  50400  360272  -0.031

## fdr 요약


In [ ]:
"""

# finance_datareader

## 설치 및 임포트
# !pip install finance_datareader
import FinanceDataReader as fdr

## 데이터 읽기
# KODEX 200 (ETF)
df2 = fdr.DataReader("069500", '2018-01-02', '2018-10-30')

eg)
import FinanceDataReader as fdr

# 예제 - ETF로 reindexing (삼전의 2번째 날의 데이터가 사라졌다.)
# 삼전(005930),코덱스200(069500)

df1 = fdr.DataReader('005930','2018-01-02','2018-10-30')
df2 = fdr.DataReader('069500','2018-01-02','2018-10-30')
df1 = df1.drop(pd.to_datetime('2018-01-03'))
df1.shape,df2.shape
# df1.head()
# df2.index # dtype='datetime64[ns]'
df1 = df1.reindex(df2.index,method="ffill")
df1.head()

"""

In [ ]:
import FinanceDataReader as fdr

# 예제 - ETF로 reindexing (삼전의 2번째 날의 데이터가 사라졌다.)
# 삼전(005930),코덱스200(069500)

df1 = fdr.DataReader('005930','2018-01-02','2018-10-30')
df2 = fdr.DataReader('069500','2018-01-02','2018-10-30')
df1 = df1.drop(pd.to_datetime('2018-01-03'))
df1.shape,df2.shape
# df1.head()
# df2.index # dtype='datetime64[ns]'
df1 = df1.reindex(df2.index,method="ffill")
df1.head()

((201, 6), (202, 6))

Open   High    Low  Close  Volume  Change
Date                                                  
2018-01-02  51380  51400  50780  51020  169485   0.001
2018-01-03  51380  51400  50780  51020  169485   0.001
2018-01-04  52120  52180  50640  51080  233909  -0.010
2018-01-05  51300  52120  51200  52120  189623   0.020
2018-01-08  52400  52520  51500  52020  167673  -0.002

## DF 요약 - 2

In [ ]:
## DF 요약 - 2

"""
- EDA : 데이터의 특성을 파악하는것
1. 메타 데이터를 통해 파악 (shape..  등)
2. 통계를 통해 파악 (describe.. 등)

df = pd.read_csv(prefix_path+"my_data/naver_finance/2015_12.csv")

# 데이터 타입에 대한 정보

df.info() # 컬럼명-Count,Dtype 등
df.dtypes.value_counts() # 플롯형 15개, obj형 1개
df.dtypes.values # -> 컬럼dtype리스트 반환
df['ticker'].dtype # 특정 컬럼 dtype('O')

# 데이터 타입 수정 
df = df.rename(columns={"ticker":"종목명"}) # 컬럼명 rename

# 데이터 자체에 대한 정보 shape,describe

df.shape
df.describe().T # 옆으로 길어질때 사용!
df.describe(include=[np.number]).T # 특정 타입만 알아보기
df.describe(exclude=[np.number]).T
#* int,int64,float,float64
#* np.object,np.float,np.float64,

## percentiles 옵션 (quantile)

df.describe(percentiles=[0.01,0.03,0.99]).T
df['PBR(배)'].quantile([0.2,0.3,0.99])
df['PBR(배)'].quantile(0.2)



"""

### DF 요약 - 2 eg

In [115]:
df = pd.read_csv(prefix_path+"my_data/naver_finance/2015_12.csv")


# 데이터 자체에 대한 정보
# df.shape
# df.describe().T # 옆으로 길어질때 사용!
# df.describe(include=[np.number]).T # 특정 타입만 알아보기
# df.describe(exclude=[np.number]).T
#* int,int64,float,float64
#* np.object,np.float,np.float64,

# percentiles 옵션
df.describe(percentiles=[0.01,0.03,0.99]).T
df['PBR(배)'].quantile([0.2,0.3,0.99])
df['PBR(배)'].quantile(0.2)


# 데이터 타입에 대한 정보

# df.info() # 컬럼명-Count,Dtype 등
# df.dtypes.value_counts() # 플롯형 15개, obj형 1개
# df.dtypes.values # -> 컬럼dtype리스트 반환
# df['ticker'].dtype # 특정 컬럼 dtype('O')

# 데이터 타입 수정 
df = df.rename(columns={"ticker":"종목명"}) # 컬럼명 rename


count      mean        std         min         1%        3%  \
매출액(억원)   680.000 30112.802 108134.170       3.561     90.991   260.989   
영업이익률(%)  680.000     3.882     13.143    -191.601    -24.020   -16.146   
순이익률(%)   680.000     7.669    151.567    -193.426    -60.643   -22.178   
당기순이익(억원) 680.000  1312.761  10133.596  -22092.438  -7180.579 -1306.169   
ROE(%)    665.000     4.512    130.083    -529.306   -172.499   -64.138   
ROA(%)    665.000     1.837      9.512    -136.813    -24.324   -12.483   
ROIC(%)   611.000    -3.009    195.156   -4685.987    -87.171   -22.647   
EPS(원)    681.000   426.081  34193.002 -844700.060 -21802.761 -7554.768   
BPS(원)    681.000 47451.880 152959.285 -230961.190    335.806   647.361   
SPS(원)    681.000 95471.752 316794.457      50.177    275.122   868.490   
PER(배)    668.000    18.921    134.916   -1435.921   -183.633   -43.725   
PBR(배)    681.000     1.582      2.040      -2.829      0.223     0.314   
PSR(배)    668.000     1.922     19.849       0.011      0.062     0.099   
price     681.000 47344.200 117063.700     158.000    860.400  1092.000   
price2    681.000 41784.562  96318.573     154.000    884.000  1056.200   

                50%         99%         max  
매출액(억원)    4692.060  467457.632 2006534.900  
영업이익률(%)      4.194      28.584      64.273  
순이익률(%)       3.067      33.191    3923.338  
당기순이익(억원)   118.918   26421.608  190601.440  
ROE(%)        5.350      47.205    3122.573  
ROA(%)        2.305      18.687      60.287  
ROIC(%)       5.208      84.221     271.957  
EPS(원)      539.109   30953.850   93713.010  
BPS(원)    10988.989  465518.476 3017474.000  
SPS(원)    22559.920 1014441.360 5553036.500  
PER(배)       11.743     261.649    2808.262  
PBR(배)        0.957      10.413      21.154  
PSR(배)        0.590       9.937     511.718  
price     12018.000  505887.200 1225000.000  
price2    10900.000  449400.000 1064000.000

0.200    0.571
0.300    0.667
0.990   10.413
Name: PBR(배), dtype: float64

0.5706600000000001

In [ ]:
# eg - 순이익률이 영업이익률을 넘은 기업의 수와,퍼센테이지를 구해라.

df = pd.read_csv(prefix_path+"my_data/naver_finance/2015_12.csv")
a = df['순이익률(%)'] > df['영업이익률(%)']
len(a),a.sum(),a.mean() # (681, 142, 0.20851688693098386)

# 681 개의 기업중 , 142개 기업이 조건을 만족, 이는 0.2 비율임.

(681, 142, 0.20851688693098386)

In [ ]:
a = np.array([[1,2,3],[2,3,4]])
a.sum(axis=0) # array([3, 5, 7])
a.sum(axis=1) # array([6, 9])


array([3, 5, 7])

array([6, 9])